### ISSUE TITLE
Completed tasks remain visible until refresh

### ISSUE THREAD

**Issue by pglezen** [delashum/obsidian-checklist-plugin#112]
## Observed Behavior

I have *Show Completed* disabled.  When I

* add a new task, or
* flip **completed** to **uncompleted**

the checklist immediately updates as I expected.  But if I

* mark the task **complete** in the checklist
* mark the task **complete** in the file
* delete the task from the file

the checklist does not disappear from the checklist until I disable and re-enable the `todo` filter.

## Configuration

| Component | Version |
|-------------|---------|
|Platform| macOS |
|Obsidian | `v0.13.19` |
|Checklist | `2.0.2` |

**Comment by timlawson-uk** [comment]
Yes, I am getting the same issues as @pglezen is describing above.

**Comment by pglezen** [comment]
This morning I noticed I am no longer experiencing this problem.  My versions of **Obsidian** and **Checklist** are still the same.  How about you, @timlawson-uk ?  Does it help if you sleep on it?

I remember that two days ago I had tried stopping and restarting Obsidian.  So that itself doesn't seem to be the magic sauce.  But today all the *misbehavior* I cited in the original issue seem to work for me now.

**Comment by timlawson-uk** [comment]
Yes, it is still happening for me @pglezen . The problem seems to be the last item you check off for any list hangs around and does not clear. 

This is my list with everything complete...
<img width="188" alt="Screenshot 2022-01-14 at 06 36 35" src="https://user-images.githubusercontent.com/69344997/149462726-2ddc9ba6-9609-4f4d-95dc-d66e7c3f1a37.png">

'Test 2' was the last item I ticked off yet it is still in the sidebar...
<img width="295" alt="Screenshot 2022-01-14 at 06 36 56" src="https://user-images.githubusercontent.com/69344997/149462800-e4605a60-758f-473e-98e3-fab1ad82f4fc.png">

**Comment by spencewenski** [comment]
I believe this is because of the caching feature that was added recently, specifically the [calculateAllItems](https://github.com/delashum/obsidian-checklist-plugin/blob/master/src/view.ts#L105) method. The method currently only updates a file's cache entry if it has a todo item -- if the file changes from having a todo item to not having one, the todo item(s) are not removed from the cache for that file.

A naive solution is to add the following to the end of the method:

```typescript
for (const [key, value] of this.itemsByFile) {
  if (!changesMap.has(key)) {
    this.itemsByFile.delete(key);
  }
}
```

There's probably a more efficient solution where we don't need to iterate through then entire cache.

**Comment by GonzalezAndrew** [comment]
I am also seeing this issue after the latest update to the plugin. Checking the console, I am not seeing anything there either. This issue seems to only affect task I have from a later date. For example, this morning I created my daily note and completed a few of my morning task. The task where checked off fine but when I try to check off a task from a previous day, it stays in the sidebar. 




![Screen Shot 2022-01-21 at 9 16 14 AM](https://user-images.githubusercontent.com/42552579/150552037-f2c41831-5f91-453f-91b8-4002658ee98b.png)
