### ISSUE TITLE
Last task for each note remains visible when checked

### ISSUE THREAD

**Issue by KennyDenvers** [delashum/obsidian-checklist-plugin#124]
(Windows 11, Obsidian v0.13.28)

I have NOT activated "show completed tasks" in options. However, it appears to me that for each note that contains tasks all tasks that I mark as completed disappear - except for the last remaining task. This is shown as completed (as indicated by the "filled" round checkbox) but will consistently NOT disappear.

(Apparently it does disappear on restart of Obsidian, which is only semi-satisfactory.)

![image](https://user-images.githubusercontent.com/90445513/156413010-340078ce-835f-4252-8fc5-c7510c20ac39.png)

**Comment by RobertWhite365** [comment]
A similar issue arises if you have single checklist item and delete it. The option to refresh the checklist does not help.  

The system finds new checklist items flawlessly. It seems that refresh does not check that existing items in the right-hand panel exist in the notes. A work-around is to disable the plugin and re-enable it.

On Win 10 if it matters.

It's a shame because it is a very useful plugin.

**Comment by bramses** [comment]
Ran into similar issue. You can force a refresh by toggling the tag in this 'settings' icon on the toolbar 
<img width="292" alt="Screen Shot 2022-05-02 at 5 57 14 PM" src="https://user-images.githubusercontent.com/3282661/166339722-52238ce5-faf7-45a3-9d5c-8a29ef888fad.png">
