### ISSUE TITLE
Plugin continually spins

### ISSUE THREAD

**Issue by arminta7** [delashum/obsidian-checklist-plugin#33]
I updated today and the pane just continually spins, whether I use a tag or not. 

Maybe this is related?

<img width="429" alt="Screen Shot 2021-03-28 at 14 53 34" src="https://user-images.githubusercontent.com/7927356/112769349-60d04500-8fd5-11eb-93ce-ebb50a2fa061.png">

**Comment by delashum** [comment]
Yeah, that's definitely an issue. After looking into it a bit, it seems like there is some ambiguity as to how frontmatter tags should be formatted. I'm expecting as array and I'm assuming you have it as a string? I will add an update to work with more formats.

**Comment by delashum** [comment]
Okay, so it looks like the supported syntax for tag metadata in frontmatter is `[tag1, tag2, ...]`. If you format your tags like that it should work fine. Let me know if you are still having issues after that.

**Comment by arminta7** [comment]
Alright, I went through and cleaned up the formatting. It's working now, thanks!

**Comment by lillianhorin** [comment]
Wondering if there's any plans to support the YAML frontmatter that looks like the following?

![image](https://user-images.githubusercontent.com/24489520/112849265-e1934d80-9076-11eb-8d99-fc5d61de3357.png)

Because the Markdown Prettifier plugin automatically reformats the tags to look like this, so having to reformat it each time is pretty time consuming.
