### ISSUE TITLE
Make tag case-insensitive

### ISSUE THREAD

**Issue by KuraFire** [delashum/obsidian-checklist-plugin#77]
I was wondering why this plugin wasn't finding any of my #TODO tags even though it seemed I was doing everything right.

Then I decided to change a tag instance to just read "#todo" as a test, and lo and behold: it immediately worked. 🥳 

Highly recommend making its lookup case-insensitive because tags are case-insensitive themselves. :)

**Comment by mochsner** [comment]
Personally, while I would've originally agreed with this request when I started (not a maintainer, just another user), I imagine one of the primary issues with would be deciding what the final tag should look like in terms of casing, since we'll need to programmatically decide on something if doing the check ourselves. I, for example, use camel casing for my tags when it's for a checklist that's for a particular "thing" at work. So if I had a tag that's called `aReallyLongTagName`, where the separation of words is important, would we convert that all to lowercase? If so, that sort of breaks functionality for me.

The "solution" I can think of to this problem would be to calculate what the majority tag casing is, and then convert the minority to that majority case style. Unfortunately, I imagine that would cause a performance regression as lists are getting recalculated every time an item is checked off. But @delashum would know more.

FWIW, you should get recommendations on tags (like below) on the newest version of Obsidian, so I think that might help get to what you're looking for @KuraFire ?
![image](https://user-images.githubusercontent.com/19310711/129135171-e99a7d08-9afe-402d-ab8d-c433f6013e30.png)
