### ISSUE TITLE
Tag based categorization: checklist tag without items inherits all items from next tag

### ISSUE THREAD

**Issue by mochsner** [delashum/obsidian-checklist-plugin#83]
Undesired/functionality here. All the tags get put in "loans" instead of "obsidian.
![image](https://user-images.githubusercontent.com/19310711/130083585-d1b9d549-3c21-4971-89b4-588c973173a8.png)

**Comment by delashum** [comment]
Well that's interesting. Definitely need to look into that one.

**Comment by delashum** [comment]
This was expected behavior. Just pushed a commit which changed behavior here, so in this case these would show up in both tags actually. Since technically that list has two tags prefixing it (since we allow for newline in between a tag and a checklist). If you had 2 newlines there instead it won't pick it up.
